name: Build and Deploy the server to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'hubble-express-server/**'
      - '.github/**'
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check Out Repo
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./hubble-express-server
          file: ./hubble-express-server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hubble-server:latest

      # Verify the pushed image
      - name: Verify Pushed Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/hubble-server:latest

      # Deploy the Docker image to an EC2 instance
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Pull the latest application image
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/hubble-server:latest
            
            # Pull the latest Redis image
            sudo docker pull redis:alpine
            
            # Stop and remove existing containers
            sudo docker stop hubble-backend || true
            sudo docker rm hubble-backend || true
            sudo docker stop redis-container || true
            sudo docker rm redis-container || true

            # Run Redis container
            sudo docker run -d --name redis-container -p ${{ secrets.REDIS_PORT }}:6379 redis:alpine

            # Run application server container
            sudo docker run -d --name hubble-backend -p 4000:4000 -e "CLIENT_URL=${{ secrets.CLIENT_URL }}" -e "DATABASE_URL= ${{ secrets.DATABASE_URL }}" -e "JWT_SECRET=${{ secrets.JWT_SECRET }}" -e "COOKIE_HTTPONLY=true" -e "REDIS_PORT=${{ secrets.REDIS_PORT }}" -e "REDIS_HOST=${{ secrets.REDIS_HOST }}" -e "CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }}" -e "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" -e "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" -e "EMAIL_ID=${{ secrets.EMAIL_ID }}" -e "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" -e "EMAIL_SMTP=${{ secrets.EMAIL_SMTP }}" -e "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" ${{ secrets.DOCKER_USERNAME }}/hubble-server:latest